import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/nav/Nav";
import { Toaster } from "react-hot-toast";
import { auth } from "@/auth/auth";
import SessionProviderComponent from "@/components/SessionProviderComponent";
import LoadResourceAuth from "@/components/resourceAuth/Load";
import LoadCompanyDepartment from "@/components/companyDepartmentSelection/loadCompanyDepartment";

const montserrat = localFont({
  src: "./fonts/Montserrat.ttf",
  variable: "--montserrat",
});

const openSans = localFont({
  src: "./fonts/OpenSans.ttf",
  variable: "--openSans",
});

const metadataInfo = {
  title: "paperless",
  description: "Generated by Max"
}

export const metadata: Metadata = {
  title: metadataInfo.title,
  description: metadataInfo.description,
  metadataBase: new URL('https://squaremaxtech.com'),
  openGraph: {
    title: metadataInfo.title,
    description: metadataInfo.description,
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const seenSession = await auth()

  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${openSans.variable} antialiased`}
      >
        <SessionProviderComponent seenSession={seenSession}>
          <Toaster position="top-center" reverseOrder={false} />
          <LoadResourceAuth />
          {seenSession !== null && <LoadCompanyDepartment session={seenSession} />}

          <Nav />

          {children}

        </SessionProviderComponent>
      </body>
    </html>
  );
}
