import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/nav/Nav";
import { Toaster } from "react-hot-toast";
import { auth } from "@/auth/auth";
import SessionProviderComponent from "@/components/SessionProviderComponent";
import LoadResourceAuth from "@/components/resourceAuth/Load";

const geist = localFont({
  src: "./fonts/Geist.ttf",
  variable: "--geist",
});

const metadataInfo = {
  title: "paperless",
  description: "Generated by Max"
}

export const metadata: Metadata = {
  title: metadataInfo.title,
  description: metadataInfo.description,
  metadataBase: new URL('https://squaremaxtech.com'),
  openGraph: {
    title: metadataInfo.title,
    description: metadataInfo.description,
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const seenSession = await auth()

  return (
    <html lang="en">
      <body
        className={`${geist.variable} antialiased`}
      >
        <SessionProviderComponent seenSession={seenSession}>
          <Toaster position="top-center" reverseOrder={false} />
          <Nav />
          <LoadResourceAuth />

          {children}
        </SessionProviderComponent>
      </body>
    </html>
  );
}
